---
title: "Assignment 1"
---

# Assignment 1

My first assignment has three parts.

## (a)

Here is the video I chose for Part A. [R vs Python \| Which is Better for Data Analysis?](https://www.youtube.com/watch?v=1gdKC5O0Pwc) The video mainly focuses on the comparison between R and Python.

#### ***Brief Summary:***

::: {align="justify"}
In this video, the presenter discusses whether Python or R is better for data analysis. Python is described as a versatile programming language, while R was initially made for statistics. The video talks about popular packages in both languages and mentions that Python is good for web applications and easy to learn, while R is better for advanced stats. The presenter suggests trying both to see which one works best for you, promoting an open-minded approach to this debate.
:::

#### ***Highlights***:

-   Python is a general-purpose programming language, while R was initially developed for statistical analysis.
-   Popular packages in R include dplyr, ggplot2, and shiny, while Python offers libraries like pandas, matplotlib, and seaborn.
-   Python is more versatile and suitable for web applications, but R excels in statistical analysis.
-   Python is easier to learn, while R offers more advanced features.

## **(b)**

## **(c)**

```{r}
options(repos = c(CRAN = "https://cran.r-project.org"))
install.packages("dslabs")
library(dslabs)
data("na_example")
na_example
# Total number of NAs in the data frame:
sum(is.na(na_example))
no_na_example <- ifelse(is.na(na_example), 0, na_example)
no_na_example
# Total number of NAs in the new data frame:
sum(is.na(no_na_example))
```
